### ISSUE TITLE
smtpd planned to be removed from stdlib

### ISSUE THREAD

**Issue by aragilar** [ICRAR/ngas#14]
[PEP 594](https://www.python.org/dev/peps/pep-0594/#deprecation-schedule) plans on removing smtpd from the standard library, it's probably worth working out what's needed to replace its usage within ngas.

**Comment by rtobar** [comment]
Thanks for pointing out! Removal is scheduled for 3.10 by the look of things, so this is still not too urgent. The recommended way to go is using [aiosmtpd](https://pypi.org/project/aiosmtpd/) which requires python 3.5+. Until we decide to drop support for it, testing with 2.7 will probably continue being based on smtpd though.

**Comment by rtobar** [comment]
This is now implemented on the `master` branch. The code still tries to import `smtpd`, but when that's not possible it then requires `aiosmtpd` to be present, and the SMTP server used for testing is implemented in terms of the latter package.

Local tests showed this is working, but sadly testing against python 3.10 in Travis is still not possible due to our dependencies not being easily available under python 3.10 (e.g., installing numpy fails at the moment). Once python 3.10 comes out officially, and wider package support is available, we can add a job in Travis.
