### ISSUE TITLE
Subscription service throws exception on Python 3

### ISSUE THREAD

**Issue by aragilar** [ICRAR/ngas#6]
When trying to run a server with a subscription on python 3
https://github.com/ICRAR/ngas/blob/52eba70f652745ab19391b70b1214788e3bb30b9/src/ngamsServer/ngamsServer/ngamsSubscriptionThread.py#L335
throws an exception due to a comparison between a string (lastSchedule) and a float (lastDelivery). The docs would suggest that lastDelivery should be a string in this case, though getSubscriberStatus returns a float (though the getSubscriberStatus docstring also suggests that lastDelivery should be a string). Should getSubscriberStatus be returning a string? Would it be useful to look at using datetimes rather than string or floats (avoiding more chances for odd comparisons)?

**Comment by rtobar** [comment]
Thanks for the report @aragilar. I've just pushed a fix to the `master` for this problem and will backport to `v11`. The commit includes also a new unit test that reproduces the original problem, as it clearly wasn't captured in our unit test suite.

There is clearly a bit of a mismatch between what the doc says and what the code is doing, most probably due to the age of the code. Regarding the data types, timestamps are stored as strings in the database (and that will continue being so unless we break backwards-compatibility), but internally the code represents them (or tries to, it clearly wasn't the case here) as seconds since the UNIX epoch, which is what `time.time()` gives you. We might want to switch to datetime in the future, but as long as we are consistent on using _A_ data type for internal timestamp representation we should be fine.

**Comment by rtobar** [comment]
@aragilar please let me know if the issue is gone with this fix, or if you still see it. If all is well I'll close the ticket.

**Comment by aragilar** [comment]
Yep, it's fixed. Thanks!
