### ISSUE TITLE
Defunct (Janitor) process after OFFLINE,ONLINE (or INIT)

### ISSUE THREAD

**Issue by szampier** [ICRAR/ngas#97]
When the ngams server is running in our configuration `ps` shows three running processes, corresponding (I think) to `main`, `data-check` and `janitor`.
If we send an `INIT` command, we end up with 2 running processes and one defunct process. We suspect the defunct process is the Janitor task.
The same issue happens when we send `OFFLINE` followed by `ONLINE`.

**Comment by rtobar** [comment]
@szampier thanks for reporting this and sorry for taking so long to respond, but I was on leave.

After trying it out I can also see the same behavior. I was able to at least duplicate the problem with the following:
 * Start the server data checker disabled (for simplicity) and started with `-autoonline`, I see two processes (main and janitor)
 * Send `OFFLINE` command, I see only the main process
 * Send `ONLINE` command, I see the main process plus a defunct one

`INIT` is just `OFFLINE` + `ONLINE` in one go, so it would be the same.

The problem was that the code starting/ending the background tasks didn't clear the `Event` object before starting the background tasks. These events are what we use to coordinate the shutdown of the background tasks when necessary. This is usually when `SIGTERM`/`SIGINT` is sent to the server, but also during the `OFFLINE` command. When shutting down the background tasks we call `event.set()` and wait for the background tasks to timely react and finish -- but we never clear the event again, so a new `ONLINE` command started the background tasks, all of which immediately finish, hence the defunct process (the server would have collected it when shutting itself down).

I'll put a patch in now for this, it should appear in master in not too long.

**Comment by rtobar** [comment]
Done, a fix for this is now on the `master` branch.
